#cargo-features = ["strip"]

[package]
name = "csv2json"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
#strip = true 
opt-level = 3

[dependencies]
